// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto

#include "masterworker.pb.h"
#include "masterworker.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace masterworker {

static const char* MasterMachine_method_names[] = {
  "/masterworker.MasterMachine/mapReduceRequest",
};

std::unique_ptr< MasterMachine::Stub> MasterMachine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MasterMachine::Stub> stub(new MasterMachine::Stub(channel));
  return stub;
}

MasterMachine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_mapReduceRequest_(MasterMachine_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MasterMachine::Stub::mapReduceRequest(::grpc::ClientContext* context, const ::masterworker::MasterRequest& request, ::masterworker::WorkerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::masterworker::MasterRequest, ::masterworker::WorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_mapReduceRequest_, context, request, response);
}

void MasterMachine::Stub::experimental_async::mapReduceRequest(::grpc::ClientContext* context, const ::masterworker::MasterRequest* request, ::masterworker::WorkerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::masterworker::MasterRequest, ::masterworker::WorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_mapReduceRequest_, context, request, response, std::move(f));
}

void MasterMachine::Stub::experimental_async::mapReduceRequest(::grpc::ClientContext* context, const ::masterworker::MasterRequest* request, ::masterworker::WorkerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_mapReduceRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::masterworker::WorkerResponse>* MasterMachine::Stub::PrepareAsyncmapReduceRequestRaw(::grpc::ClientContext* context, const ::masterworker::MasterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::masterworker::WorkerResponse, ::masterworker::MasterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_mapReduceRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::masterworker::WorkerResponse>* MasterMachine::Stub::AsyncmapReduceRequestRaw(::grpc::ClientContext* context, const ::masterworker::MasterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncmapReduceRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

MasterMachine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterMachine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterMachine::Service, ::masterworker::MasterRequest, ::masterworker::WorkerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterMachine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::masterworker::MasterRequest* req,
             ::masterworker::WorkerResponse* resp) {
               return service->mapReduceRequest(ctx, req, resp);
             }, this)));
}

MasterMachine::Service::~Service() {
}

::grpc::Status MasterMachine::Service::mapReduceRequest(::grpc::ServerContext* context, const ::masterworker::MasterRequest* request, ::masterworker::WorkerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace masterworker

